# Roles
ROLE_TECHNICIAN = "Technician"
ROLE_SUPERVISOR = "Supervisor"
ROLE_ADMIN = "Admin"

# Asset search config
DEFAULT_ASSET_RADIUS_METERS = 50.0

# Redis Cache TTLs
REDIS_SESSION_TTL_SECONDS = 3600  # 1 hour
REDIS_RATE_LIMIT_TTL_SECONDS = 60  # 1 minute

# Conversation Config
MAX_HISTORY_BEFORE_SUMMARIZATION = 10
EMBEDDING_MODEL_DIMENSION = 1536
